version: '3.8'
services:
  web:
    build: .
    ports:
      - "8188:8188"
    volumes:
      - .:/app
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

